force-app/main/default/objects/Imoveis__c/Imoveis__c.object-meta.xml
<CustomObject>
    <description>Exibe informações de imóveis</description>
    <label>Imóveis</label>
    <nameField>
        <displayFormat>IMO-{0000}</displayFormat>
        <label>Nome de imóveis</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imoveis__c/fields/Banheiro__c.field-meta.xml
<CustomField>
    <fullName>Banheiro__c</fullName>
    <inlineHelpText>Insira a quantidade de banheiros</inlineHelpText>
    <label>Banheiro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Copa__c.field-meta.xml
<CustomField>
    <fullName>Copa__c</fullName>
    <inlineHelpText>Insira a quantidade de copas</inlineHelpText>
    <label>Copa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Garagem__c.field-meta.xml
<CustomField>
    <fullName>Garagem__c</fullName>
    <inlineHelpText>Insira a quantidade de garagens</inlineHelpText>
    <label>Garagem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Quantidade_de_Quartos__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_Quartos__c</fullName>
    <inlineHelpText>Insira a quantidade de quartos</inlineHelpText>
    <label>Quantidade de Quartos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Sala__c.field-meta.xml
<CustomField>
    <fullName>Sala__c</fullName>
    <inlineHelpText>Insira a quantidade de salas</inlineHelpText>
    <label>Sala</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Suite__c.field-meta.xml
<CustomField>
    <fullName>Suite__c</fullName>
    <inlineHelpText>Insira a quantidade de suites</inlineHelpText>
    <label>Suite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Tipo_do_Imovel__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_Imovel__c</fullName>
    <description>Escola o tipo do imóvel</description>
    <label>Tipo do Imóvel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nenhum</fullName>
                <default>true</default>
                <label>Nenhum</label>
            </value>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Apartamento</fullName>
            </value>
            <value>
                <fullName>sítio</fullName>
                <label>Sítio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <inlineHelpText>Digite o valor do imóvel</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ImobiliariaController.cls
public class ImobiliariaController {
    
    public Integer quartos {get; set;}
    public Integer banheiros {get; set;}
    public Integer salas {get; set;}
    public Integer copas {get; set;}
    public Integer suites {get; set;}
    public Integer garagem {get; set;}
    public Integer valor {get; set;}
    public String tipoImovel {get; set;}
    
    
    public List<SelectOption> getMyOptions() {
        
        Schema.DescribeFieldResult describeResult = Imoveis__c.Tipo_do_Imovel__c.getDescribe();
        
        List<Schema.PicklistEntry> entries = describeResult.getPickListValues();
        
        List<SelectOption> optionsToReturn = new List<SelectOption>();
        
        for (Schema.PicklistEntry pEntry : entries) {
            
            if (pEntry.isActive()) {
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }
        
        return optionsToReturn;
    }
    
    public void salvarImoveis() {
        
        Imoveis__c imv = new Imoveis__c();
        
        imv.Quantidade_de_Quartos__c = quartos;
        imv.Banheiro__c = banheiros;
        imv.Sala__c = salas;
        imv.Copa__c = copas;
        imv.Suite__c = suites;
        imv.Garagem__c = garagem;
        imv.Valor__c = valor;
        imv.Tipo_do_Imovel__c = tipoImovel;
        
        try{
            if(imv.Tipo_do_Imovel__c != 'Nenhum' && imv.Tipo_do_Imovel__c != null)	{
                
            	ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, 'Imóvel cadastrado com sucesso!'));
                
                insert imv;
                
                quartos = null;
                banheiros = null;
                salas = null;
                copas = null;
                suites = null;
                garagem = null;
                valor = null;
                tipoImovel = null;
                
            }else{
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'O campo tipo do imóvel deve ser preenchido!'));
            }
        	            
        }catch(DmlException e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Por favor verifique todos os campos antes de enviar'));
		}
        
	}
}