force-app/main/default/objects/Imoveis__c/Imoveis__c.object-meta.xml
<CustomObject>
    <description>Exibe informações de imóveis</description>
    <label>Imóveis</label>
    <nameField>
        <displayFormat>IMO-{0000}</displayFormat>
        <label>Nome de imóveis</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imoveis__c/fields/Nivel_do_Imovel__c.field-meta.xml
<CustomField>
    <fullName>Nivel_do_Imovel__c</fullName>
    <inlineHelpText>Nível do imóvel preenchido automaticamente</inlineHelpText>
    <label>Nível do Imóvel</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Imoveis__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <inlineHelpText>Digite o valor do imóvel</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ImovelTriggerHandler.cls
public class ImovelTriggerHandler {
    
    public static void insertOrUpdateNivel(List<Imoveis__c> imovel) {
		
        List<Imoveis__c> imvValor = imovel;
        
        for(Imoveis__c imv : imvValor)   {
			
            if(imv.Valor__c <= 5000)
                imv.Nivel_do_Imovel__c = 'Bronze';
                
            if(imv.Valor__c >= 50000 && imv.Valor__c < 100000)
                imv.Nivel_do_Imovel__c = 'Prata';
        
            if(imv.Valor__c >= 100000)
                imv.Nivel_do_Imovel__c = 'Ouro';
        }
    }

}